# Generated by Django 2.2.6 on 2019-10-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50, verbose_name='批次名称')),
            ],
            options={
                'verbose_name': '录取批次',
                'verbose_name_plural': 'AdmissionBatchs',
            },
        ),
        migrations.CreateModel(
            name='AdmissionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='年份')),
            ],
            options={
                'verbose_name': '招生年份',
                'verbose_name_plural': 'AdmissionYears',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_to', models.CharField(max_length=50, verbose_name='隶属于')),
            ],
            options={
                'verbose_name': '隶属关系',
                'verbose_name_plural': 'Affiliations',
            },
        ),
        migrations.CreateModel(
            name='ExamDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
            ],
            options={
                'verbose_name': '高考分科',
                'verbose_name_plural': 'ExamDivisions',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='排名')),
            ],
            options={
                'verbose_name': '综合排名',
                'verbose_name_plural': 'Ranks',
            },
        ),
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50, verbose_name='特色')),
            ],
            options={
                'verbose_name': '院校特色',
                'verbose_name_plural': 'SchoolFeatures',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='高校性质')),
            ],
            options={
                'verbose_name': '高校性质',
                'verbose_name_plural': 'SchoolLevels',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='类型')),
            ],
            options={
                'verbose_name': '高校类型',
                'verbose_name_plural': 'SchoolTypes',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='院校名称')),
                ('is_key_universities', models.BooleanField(default=False, verbose_name='是否重点院校')),
                ('home_page', models.CharField(blank=True, max_length=255, null=True, verbose_name='院校主页')),
                ('features', models.CharField(blank=True, max_length=255, null=True, verbose_name='院校特色')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='das.Affiliation')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='das.SchoolLevel')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='das.Province')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='das.Rank')),
                ('school_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='das.SchoolType')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
