# Generated by Django 2.2.6 on 2019-10-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份', 'verbose_name_plural': '省份'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '综合排名', 'verbose_name_plural': '综合排名'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='das.Province', verbose_name='省份'),
        ),
        migrations.CreateModel(
            name='Univercity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='院校名称')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='univercities', to='das.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '高校',
                'verbose_name_plural': '高校',
            },
        ),
    ]
