# Generated by Django 2.2.6 on 2019-10-31 17:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('das', '0003_auto_20191031_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionyear',
            options={'verbose_name': '招生年份', 'verbose_name_plural': '招生年份'},
        ),
        migrations.AddField(
            model_name='univercity',
            name='project_tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='univercity',
            name='total_rank',
            field=models.IntegerField(default=999, verbose_name=''),
        ),
    ]
