# Generated by Django 2.2.6 on 2019-10-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0004_auto_20191031_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univercity',
            old_name='project_tag',
            new_name='project_tags',
        ),
    ]
