# Generated by Django 2.2.6 on 2019-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0005_auto_20191031_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('理科', '理科'), ('文科', '文科')], max_length=2, verbose_name='专业类型')),
                ('name', models.CharField(max_length=255, verbose_name='专业')),
            ],
            options={
                'verbose_name': '学科专业',
                'verbose_name_plural': '学科专业',
            },
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '排名', 'verbose_name_plural': '排名'},
        ),
        migrations.AddField(
            model_name='univercity',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='是否民办院校'),
        ),
    ]
