# Generated by Django 2.2.6 on 2019-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0007_auto_20191103_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100, unique=True, verbose_name='批次名称')),
            ],
            options={
                'verbose_name': '录取批次',
                'verbose_name_plural': '录取批次',
            },
        ),
    ]
