# Generated by Django 2.2.6 on 2019-11-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0008_admissionbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('admission_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorelines', to='das.AdmissionYear')),
            ],
            options={
                'verbose_name': '分数线',
                'verbose_name_plural': '分数线',
            },
        ),
    ]
