# Generated by Django 2.2.6 on 2019-11-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0010_auto_20191103_2131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scoreline',
            unique_together={('subject_type', 'admission_batch', 'admission_year')},
        ),
    ]
