# Generated by Django 2.2.6 on 2019-11-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0011_auto_20191103_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnivercityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='代号')),
                ('univercity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univercity_codes', to='das.Univercity', verbose_name='高校')),
            ],
            options={
                'verbose_name': '院校代号',
                'verbose_name_plural': '院校代号',
            },
        ),
    ]
