# Generated by Django 2.2.6 on 2019-11-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0013_auto_20191104_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_amount', models.IntegerField(default=0, verbose_name='计划数')),
                ('actual_amount', models.IntegerField(default=0, verbose_name='实录数')),
                ('highest_score', models.FloatField(default=0.0, verbose_name='最高分')),
                ('lowest_score', models.FloatField(default=0.0, verbose_name='最低分')),
                ('average_score', models.FloatField(default=0.0, verbose_name='平均分')),
                ('admission_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.AdmissionBatch', verbose_name='录取批次')),
                ('admission_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.AdmissionYear', verbose_name='录取年份')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.SubjectType', verbose_name='学科类型')),
                ('univercity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.UnivercityCode', verbose_name='院校代号')),
            ],
            options={
                'verbose_name': '招生计划',
                'verbose_name_plural': '招生计划',
            },
        ),
    ]
