# Generated by Django 2.2.6 on 2019-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0014_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='lowest_rank',
            field=models.IntegerField(default=0, verbose_name='最低位次'),
        ),
    ]
