# Generated by Django 2.2.6 on 2019-11-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0015_plan_lowest_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '历年招生数据', 'verbose_name_plural': '历年招生数据'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': '学科档次', 'verbose_name_plural': '学科档次'},
        ),
        migrations.AlterModelOptions(
            name='scoreline',
            options={'verbose_name': '历年分数线', 'verbose_name_plural': '历年分数线'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科门类', 'verbose_name_plural': '学科门类'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': '考生类型', 'verbose_name_plural': '考生类型'},
        ),
        migrations.AlterModelOptions(
            name='univercity',
            options={'verbose_name': '院校信息', 'verbose_name_plural': '院校信息'},
        ),
        migrations.AlterModelOptions(
            name='univercitycode',
            options={'verbose_name': '院校代码', 'verbose_name_plural': '院校代码'},
        ),
        migrations.AddField(
            model_name='plan',
            name='highest_rank',
            field=models.IntegerField(default=0, verbose_name='最高位次'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='das.SubjectType', verbose_name='考生类型'),
        ),
        migrations.AddField(
            model_name='univercitycode',
            name='univercity_name_alias',
            field=models.CharField(default=1, max_length=255, verbose_name='学校名称(含招生条件备注)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='subject_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.SubjectType', verbose_name='考生类型'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='univercity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='das.UnivercityCode', verbose_name='院校代码'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=50, verbose_name='档次'),
        ),
        migrations.AlterField(
            model_name='univercitycode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='univercitycode',
            name='univercity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='univercity_codes', to='das.Univercity', verbose_name='高校'),
        ),
    ]
