# Generated by Django 2.2.6 on 2019-11-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0017_remove_subject_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='highest_score',
            field=models.IntegerField(default=0, verbose_name='最高分'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='lowest_score',
            field=models.IntegerField(default=0, verbose_name='最低分'),
        ),
    ]
