# Generated by Django 2.2.6 on 2019-11-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0018_auto_20191107_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='average_score',
            field=models.IntegerField(default=0, verbose_name='平均分'),
        ),
        migrations.CreateModel(
            name='ScoreStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('number', models.IntegerField(verbose_name='人数')),
                ('cumulative_number', models.IntegerField(verbose_name='累计人数')),
                ('admission_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_statistics', to='das.AdmissionYear', verbose_name='高考年份')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_statistics', to='das.SubjectType', verbose_name='考生类型')),
            ],
            options={
                'verbose_name': 'ScoreStatistic',
                'verbose_name_plural': 'ScoreStatistics',
            },
        ),
    ]
