# Generated by Django 2.2.6 on 2019-11-27 16:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('das', '0019_auto_20191127_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorestatistic',
            options={'verbose_name': '考生成绩统计表', 'verbose_name_plural': '考生成绩统计表'},
        ),
        migrations.AddField(
            model_name='city',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='province',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签'),
        ),
    ]
