# Generated by Django 2.2.6 on 2019-11-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0020_auto_20191127_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='average_rank',
            field=models.IntegerField(default=0, verbose_name='平均位次'),
        ),
    ]
