# Generated by Django 2.2.6 on 2019-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0021_plan_average_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='univercitycode',
            name='page1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='挑大学选专业书页码'),
        ),
        migrations.AddField(
            model_name='univercitycode',
            name='page2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='汇编书页码'),
        ),
    ]
