# Generated by Django 2.2.6 on 2019-12-03 16:40

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('das', '0022_auto_20191202_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='province',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='das.TaggedProvince', to='taggit.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='taggedprovince',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='das.Province'),
        ),
        migrations.AddField(
            model_name='taggedprovince',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='das_taggedprovince_items', to='taggit.Tag'),
        ),
    ]
