# Generated by Django 2.2.6 on 2019-12-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('das', '0025_auto_20191208_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstatistic',
            name='r1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planstatistic',
            name='r7',
            field=models.IntegerField(default=0),
        ),
    ]
